#!/usr/bin/env python3
"""Generate the committed coverage report from an author's registry.

Usage:
    uv run scripts/report_coverage.py \
        --registry registry/cankar.jsonl --author "Ivan Cankar" \
        --out registry/coverage-cankar.md
"""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path

from cankar.corpus.registry import Registry, WorkRecord


def work_status(w: WorkRecord) -> str:
    statuses = {(s.source, s.status) for s in w.sources}
    if any(st == "ingested" for _, st in statuses):
        srcs = sorted({src for src, st in statuses if st == "ingested"})
        return f"ingested ({'+'.join(srcs)})"
    if any(st == "candidate" for _, st in statuses):
        return "candidate (text exists, not fetched)"
    if any(st.startswith("skipped") for _, st in statuses):
        return next(st for _, st in statuses if st.startswith("skipped"))
    return "missing (no usable source known)"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--registry", required=True, type=Path)
    ap.add_argument("--author", required=True)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    reg = Registry.load(args.registry, args.author)
    rows = sorted(reg.works.values(), key=lambda w: w.work_id)
    counts = Counter(work_status(w) for w in rows)

    lines = [
        f"# Coverage - {args.author}",
        "",
        f"Generated by `scripts/report_coverage.py` from `{args.registry}`. Do not edit by hand.",
        "",
        f"**{len(rows)} known works.**",
        "",
        "| Status | Works |",
        "|---|---|",
        *[f"| {k} | {v} |" for k, v in counts.most_common()],
        "",
        "| Work | Year | Genre | Status | Sources |",
        "|---|---|---|---|---|",
    ]
    for w in rows:
        srcs = "; ".join(f"{s.source}:{s.status}" for s in w.sources) or "-"
        flags = f" [{', '.join(w.flags)}]" if w.flags else ""
        lines.append(
            f"| {w.title}{flags} | {w.year or ''} | {w.genre or ''} | {work_status(w)} | {srcs} |"
        )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}: {len(rows)} works")
    for k, v in counts.most_common():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
