"""Generated-report contract - one place defines the marker and write shape.

Two classes of file live in registry/reports/ (the README there is the
governed-dir contract, ADR 0007):

- drift-checked: regenerated byte-identically in CI from committed inputs
  (coverage, collisions) - `cankar corpus report --all && git diff`
- snapshot: computed from gitignored data/, regeneration is manual
  (quality, near-duplicates) - CI cannot rebuild these; do NOT fold them
  into `report --all` or the drift gate goes red in CI

The marker line encodes which class a report is; four writers share this
shape (rule of three, design-review 2026-07).
"""

from __future__ import annotations

from pathlib import Path


def generated_marker(command: str, *, snapshot: bool) -> str:
    tail = "snapshot over gitignored data" if snapshot else "do not edit by hand"
    return f"<!-- GENERATED by `{command}` - {tail} -->"


def write_report(out: Path, lines: list[str]) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
